name: Deploy on Develop

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Build Website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Build the website using Parcel
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
