name: Deploy to GitHub Pages

on:
  push:
    branches:
      - develop

permissions:
  pages: write
  id-token: write

jobs:
  linting-develop-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4


      - name: Lint HTML files (HTMLHint)
        run: npx htmlhint "**/*.html"

      - name: Lint CSS files (Stylelint)
        run: npx stylelint "**/*.css"

      - name: Test Building With Parcel
        run: npx parcel build "./src/blog.html" --dist-dir "./dist" --public-url "./"