name: PR Validation

on:
  pull_request:
    branches: 
          - develop

jobs:
  lint:
    name: Lint HTML and CSS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Linting Tools
        run: |
          npm install -g htmlhint stylelint stylelint-config-standard

      - name: Run HTMLHint
        run: npx htmlhint "**/*.html"

      - name: Run Stylelint
        run: npx stylelint "**/*.css"

  build:
    name: Build Website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Parcel
        run: npm install parcel

      - name: Build Website
        run: npx parcel build ./src/*.html --dist-dir ./dist